### ISSUE TITLE
Getting CKR_ARGUMENTS_BAD when signing with ECDSA

### ISSUE THREAD

**Issue by gergof** [PeculiarVentures/pkcs11js#105]
After upgrading to nodejs 18 the following code no longer works:
```js
const session = slot.open();
session.login('xxx', graphene.UserType.USER);
const sign = session.createSign('ECDSA_SHA256', key);
for (;;) {
	const it = dataIterator.next();
	if (it.done) {
		break;
	}
	sign.update(it.value);
}
const signature = sign.final();
```

I'm getting the following error at `sign.final()`:
```
Pkcs11Error: CKR_ARGUMENTS_BAD
    at prepareError (xxx/node_modules/pkcs11js/index.js:63:12)
    at handleError (xxx/node_modules/pkcs11js/index.js:72:9)
    at PKCS11.<anonymous> (xxx/node_modules/pkcs11js/index.js:90:7)
    at PKCS11.prototype.<computed> [as C_SignFinal] (xxx/node_modules/pkcs11js/index.js:124:30)
    at Sign.final (xxx/node_modules/graphene-pk11/build/cjs/crypto/sign.js:29:30)
```

I'm using a yubikey 5 with the graphene-pk11 library. The error was not present on node 16 and if I downgrade the nodejs version it disappears.

**Comment by gergof** [comment]
I have found the cause of the problem and the solution. The pkcs11 library (YKCS11) I was using was compiled against openssl1 (the one bundled with node 16), but node 18 comes with openssl3. I had to rebuild YKCS11 with openssl3 and it works again as expected.
