### ISSUE TITLE
Using `pkcs11js` and native `crypto` within one runtime causes errors

### ISSUE THREAD

**Issue by christopherhex** [PeculiarVentures/pkcs11js#17]
Hi, 

We are using the `pkcs11js` library, version `1.0.9` in combination with SoftHSMv2.  

Everything worked fine until recently we added a module that relies on the native `crypto` module for signing purposes. Once the `pkcs11js` lib is loaded the signing fails, complaining about a shared library that could not be loaded. In the demo snippet below, sign try 1 works and sign try 2 fails. 

Any hints on what the root cause might be, an maybe some hints for a solution? It looks that both libraries are accessing the same (libcrypto?) shared library, causing issues. 

**Node Version:** `8.4.0`

### Demo Snippet
```javascript
const crypto = require('crypto');
const pkcs11js = require('pkcs11js');
const fs = require('fs');

const privKey = fs.readFileSync('./test');
const privKeyString = privKey.toString('ascii'); 


function mainTest() {


  const thing = 'eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlRGVTNDUTNYNTgifQ.eyJpYXQiOjE1MDcyNzU5NTAsImlzcyI6IjcySzhRV1ZSRVQifQ';
  console.log('CREATE SIGN');
  
  // SIGN TRY 1
  const signer = crypto.createSign('RSA-SHA256');
  console.log('SIGNING')
  const res = (signer.update(thing), signer.sign(privKey));
  console.log(res);
  
  // LOAD PKCS11 With SoftHSM
  console.log('LOAD PKCS11');
  const pkcs11 = new pkcs11js.PKCS11();
  pkcs11.load('/usr/local/lib/softhsm/libsofthsm2.so');
  pkcs11.C_Initialize();
  const slots = pkcs11.C_GetSlotList(true);
  const slot = slots[0];
  const session = pkcs11.C_OpenSession(slot, pkcs11js.CKF_RW_SESSION | pkcs11js.CKF_SERIAL_SESSION);
  pkcs11.C_Login(session, 1, "1234");

  // SIGN TRY 2
  const signer2 = crypto.createSign('RSA-SHA256');
  console.log('SIGNING 2')
  const res2 = (signer2.update(thing), signer2.sign(privKey));
  console.log(res2);
}

try {
  mainTest();
} catch(e) {
  console.log("ERROR");
  console.log(e);
}
```

### Resulting Error
```
Error: error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library
    at Sign.sign (crypto.js:329:26)
    at mainTest (/usr/src/test/app.js:38:48)
    at Object.<anonymous> (/usr/src/test/app.js:47:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
```

**Comment by microshine** [comment]
@christopherhex I ran your code. It works for me without any errors.

```
> node ./test1
CREATE SIGN
SIGNING
<Buffer 1e 04 c9 3d 0a 6d 4d 71 ae 17 aa e2 80 11 68 f6 75 97 be 08 40 4a 6c f0 37 bd 52 bb ba 99 2f 7f 67 17 3e 34 31 df 71 9e 73 6a 91 1b 1c a9 3a 38 df 50... >
LOAD PKCS11
SIGNING 2
<Buffer 1e 04 c9 3d 0a 6d 4d 71 ae 17 aa e2 80 11 68 f6 75 97 be 08 40 4a 6c f0 37 bd 52 bb ba 99 2f 7f 67 17 3e 34 31 df 71 9e 73 6a 91 1b 1c a9 3a 38 df 50... >
```

MacOS Sierra 10.12.6
node v6.11.2

It looks problems is not in `pkcs11js` module. It allows to use SoftHSM lib until crypto operation.
SoftHSM uses OpenSSL crypto implementation and nodejs crypto uses it too. I think this is a reason of libraries conflict

Error log is from nodejs crypto module (pkcs11js doesn't have JS implementation)
```js
// crypto.js

Sign.prototype.sign = function(options, encoding) {
  if (!options)
    throw new Error('No key provided to sign');

  var key = options.key || options;
  var passphrase = options.passphrase || null;
  var ret = this._handle.sign(toBuf(key), null, passphrase);

  encoding = encoding || exports.DEFAULT_ENCODING;
  if (encoding && encoding !== 'buffer')
    ret = ret.toString(encoding);

  return ret;
};
```

I don't have any ideas how to resolve it

**Comment by rmhrisk** [comment]
Yes, sounds like maybe two different versions of OpenSSL are involved?

**Comment by microshine** [comment]
@christopherhex Have you resolved library conflict?

**Comment by christopherhex** [comment]
Hi @microshine, 

Sorry for the late reply. Still have to investigate further as we managed to work around the issue. 
Hopefully I can find some time to further investigate this next week. 

The problem seems to be something else then the pkcs11js lib so will close issue for now 😊

Thanks for the feedback !
