### ISSUE TITLE
Error: Win32 error 126     at Error (native) PKCS11::Load:129

### ISSUE THREAD

**Issue by anlopes123** [PeculiarVentures/pkcs11js#20]
when running the tests this error occurred which can be
D:\ProjetoJs\Desktop\pocDesktop\Certificado\graphene\graphene>npm run test

> graphene-pk11@2.0.28 test D:\ProjetoJs\Desktop\pocDesktop\Certificado\graphene\graphene
> mocha

  AES
    1) "before all" hook
    2) "after all" hook

  Digest
    3) "before all" hook
    4) "after all" hook

  ECDSA
    5) "before all" hook
    6) "after all" hook

  Module
    7) load
    8) initialize/finalize
    9) getSlots
    10) props

  Object
    11) "before all" hook
    12) "after all" hook

  RSA
    13) "before all" hook
    14) "after all" hook

  Session
    15) "before all" hook
    16) "after all" hook

  Slot
    17) "before all" hook
    18) "after all" hook

  0 passing (20ms)
  18 failing

  1) AES "before all" hook:
     Error: Win32 error 126
    at Error (native) PKCS11::Load:129
      at Function.Module.load (build\module.js:44:13)
      at Context.<anonymous> (test\aes.js:30:16)

  2) AES "after all" hook:
     TypeError: Cannot read property 'finalize' of undefined
      at Context.<anonymous> (test\aes.js:43:13)

  3) Digest "before all" hook:
     Error: Win32 error 126
    at Error (native) PKCS11::Load:129
      at Function.Module.load (build\module.js:44:13)
      at Context.<anonymous> (test\digest.js:13:22)

  4) Digest "after all" hook:
     TypeError: Cannot read property 'closeAll' of undefined
      at Context.<anonymous> (test\digest.js:19:14)

  5) ECDSA "before all" hook:
     Error: Win32 error 126
    at Error (native) PKCS11::Load:129
      at Function.Module.load (build\module.js:44:13)
      at Context.<anonymous> (test\ec.js:30:22)

  6) ECDSA "after all" hook:
     TypeError: Cannot read property 'finalize' of undefined
      at Context.<anonymous> (test\ec.js:43:13)

  7) Module load:
     Error: Win32 error 126
    at Error (native) PKCS11::Load:129
      at Function.Module.load (build\module.js:44:13)
      at Context.<anonymous> (test\module.js:16:23)

  8) Module initialize/finalize:
     AssertionError [ERR_ASSERTION]: Got unwanted exception.
      at innerThrows (assert.js:653:7)
      at Function.doesNotThrow (assert.js:665:3)
      at Context.<anonymous> (test\module.js:20:16)

  9) Module getSlots:
     Error: Win32 error 126
    at Error (native) PKCS11::Load:129
      at Function.Module.load (build\module.js:44:13)
      at Context.<anonymous> (test\module.js:29:26)

  10) Module props:
     Error: Win32 error 126
    at Error (native) PKCS11::Load:129
      at Function.Module.load (build\module.js:44:13)
      at Context.<anonymous> (test\module.js:39:26)

  11) Object "before all" hook:
     Error: Win32 error 126
    at Error (native) PKCS11::Load:129
      at Function.Module.load (build\module.js:44:13)
      at Context.<anonymous> (test\object.js:14:22)

  12) Object "after all" hook:
     TypeError: Cannot read property 'logout' of undefined
      at Context.<anonymous> (test\object.js:25:17)

  13) RSA "before all" hook:
     Error: Win32 error 126
    at Error (native) PKCS11::Load:129
      at Function.Module.load (build\module.js:44:13)
      at Context.<anonymous> (test\rsa.js:30:22)

  14) RSA "after all" hook:
     TypeError: Cannot read property 'finalize' of undefined
      at Context.<anonymous> (test\rsa.js:40:13)

  15) Session "before all" hook:
     Error: Win32 error 126
    at Error (native) PKCS11::Load:129
      at Function.Module.load (build\module.js:44:13)
      at Context.<anonymous> (test\session.js:13:22)

  16) Session "after all" hook:
     TypeError: Cannot read property 'finalize' of undefined
      at Context.<anonymous> (test\session.js:21:13)

  17) Slot "before all" hook:
     Error: Win32 error 126
    at Error (native) PKCS11::Load:129
      at Function.Module.load (build\module.js:44:13)
      at Context.<anonymous> (test\slot.js:12:22)

  18) Slot "after all" hook:
     TypeError: Cannot read property 'finalize' of undefined
      at Context.<anonymous> (test\slot.js:17:13)

npm ERR! code ELIFECYCLE
npm ERR! errno 18
npm ERR! graphene-pk11@2.0.28 test: `mocha`
npm ERR! Exit status 18
npm ERR!
npm ERR! Failed at the graphene-pk11@2.0.28 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Anizair\AppData\Roaming\npm-cache\_logs\2017-10-19T13_06_27_398Z-debug.log

I'm using Windows 7 64bit with SoftHSM2

**Comment by microshine** [comment]
> Win32 Error Code 126: The specified module could not be found.

`pkcs11js` uses uses `libsofthsm2` library for tests

If you want to run tests on Windows you have to change [path to library](https://github.com/PeculiarVentures/pkcs11js/blob/master/test/test.js#L8).
