### ISSUE TITLE
CKR_GENERAL_ERROR:5

### ISSUE THREAD

**Issue by ogeday26** [PeculiarVentures/pkcs11js#30]
I am developing in windows environment. I am getting such an error.

```
PS C:\Users\thzbr\Desktop\test> node .\app.js
C:\Users\thzbr\Desktop\test\app.js:7
pkcs11.C_Initialize();
       ^

Error: CKR_GENERAL_ERROR:5
    at Error (native) PKCS11::C_Initialize:170
    at Object.<anonymous> (C:\Users\thzbr\Desktop\test\app.js:7:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by ogeday26** [comment]
I was testing example 1. I just introduced softhsm2.dll.

```
var pkcs11js = require("pkcs11js");

var pkcs11 = new pkcs11js.PKCS11();
pkcs11.load("lib/softhsm2-x64.dll");


pkcs11.C_Initialize();

try {
    // Getting info about PKCS11 Module
    var module_info = pkcs11.C_GetInfo();

    // Getting list of slots
    var slots = pkcs11.C_GetSlotList(true);
    var slot = slots[0];

    // Getting info about slot
    var slot_info = pkcs11.C_GetSlotInfo(slot);
    // Getting info about token
    var token_info = pkcs11.C_GetTokenInfo(slot);

    // Getting info about Mechanism
    var mechs = pkcs11.C_GetMechanismList(slot);
    var mech_info = pkcs11.C_GetMechanismInfo(slot, mechs[0]);

    var session = pkcs11.C_OpenSession(slot, pkcs11js.CKF_RW_SESSION | pkcs11js.CKF_SERIAL_SESSION);

    // Getting info about Session
    var info = pkcs11.C_GetSessionInfo(session);
    pkcs11.C_Login(session, 1, "password");

    /**
    * Your app code here
    */

    pkcs11.C_Logout(session);
    pkcs11.C_CloseSession(session);
}
catch(e){
    console.error(e);
}
finally {
    pkcs11.C_Finalize();
}
```

**Comment by microshine** [comment]
[C_Initialize](https://github.com/opendnssec/SoftHSMv2/blob/d7be6f95df8620ad42350c8c0fa0ea5786d04a47/src/lib/SoftHSM.cpp#L369) source code for SoftHSMv2. It has many checks for `CKR_GENERAL_ERROR`

Can you check SoftHSMv2 logs for error details?
https://github.com/opendnssec/SoftHSMv2#log-information
