### ISSUE TITLE
Unable to Install pkcs11js

### ISSUE THREAD

**Issue by Swhite215** [PeculiarVentures/pkcs11js#59]
Node Version: 12.16.3
NPM Version: 6.14.4

I am getting this error when running npm install in my project directory. Is this an issue with my node version?

```
verbose stack Error: pkcs11js@1.0.17 install: `node-gyp rebuild`
8341 verbose stack Exit status 1
8341 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
8341 verbose stack     at EventEmitter.emit (events.js:310:20)
8341 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
8341 verbose stack     at ChildProcess.emit (events.js:310:20)
8341 verbose stack     at maybeClose (internal/child_process.js:1021:16)
8341 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
8342 verbose pkgid pkcs11js@1.0.17
8343 verbose cwd /PATH/PATH/PATH
8344 verbose Darwin 19.3.0
8345 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
8346 verbose node v12.16.3
8347 verbose npm  v6.14.4
8348 error code ELIFECYCLE
8349 error errno 1
8350 error pkcs11js@1.0.17 install: `node-gyp rebuild`
8350 error Exit status 1
8351 error Failed at the pkcs11js@1.0.17 install script.
```

**Comment by microshine** [comment]
@Swhite215 Do you have a log file? It's not clear why you've got that error

I've got a test result. It works fine for me
```log
npm i pkcs11js

> pkcs11js@1.0.21 install /private/tmp/p11-test/node_modules/pkcs11js
> node-gyp rebuild

  CXX(target) Release/obj.target/pkcs11/src/main.o
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.4.0
...
End of search list.
  SOLINK_MODULE(target) Release/pkcs11.node
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN p11-test@1.0.0 No description
npm WARN p11-test@1.0.0 No repository field.

+ pkcs11js@1.0.21
added 2 packages from 9 contributors and audited 2 packages in 25.696s
found 0 vulnerabilities
```

### Versions
```
Node: v12.16.3
Npm: 6.14.4
```

**Comment by anonymousdplantgit** [comment]
I am getting this error when running npm install in my project directory, do you have any idea what causes this?
Node: v10.15.3
Npm: 6.4.1

temp\Desktop\eid\eid-reader-angular\node_modules\pkcs11js>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to verify the first certificate
gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
gyp ERR! stack     at TLSSocket.emit (events.js:189:13)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:633:8)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\aitsaids\Desktop\eid\eid-reader-angular\node_modules\pkcs11js
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by donskov** [comment]
Hello @anonymousdplantgit . Try to use https://github.com/nodejs/node-gyp/issues/1587#issuecomment-503885419

**Comment by microshine** [comment]
Strange error from the log `Error: unable to verify the first certificate`.

Try to disable certificate validation using [NODE_TLS_REJECT_UNAUTHORIZED](https://nodejs.org/api/cli.html#cli_node_tls_reject_unauthorized_value) environment variable

```
set NODE_TLS_REJECT_UNAUTHORIZED=0
npm install pkcs11js
```
