### ISSUE TITLE
load error with electron -v 11 

### ISSUE THREAD

**Issue by abdalahshaban** [PeculiarVentures/pkcs11js#68]
Error: Win32 error 126
    at Error (native) PKCS11::Load:136
    at IpcMainImpl.<anonymous> (D:\test_app\electron-angular-demo\electron\dist\main.js:105:20)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:157:8867)
    at Object.emit (events.js:315:20) error

**Comment by abdalahshaban** [comment]
i fixed it
